# Generated by Django 4.1.7 on 2023-04-26 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0001_initial'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='expert',
            field=models.ForeignKey(blank=True, limit_choices_to={'user__is_expert': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expert_task', to='experts.experts'),
        ),
    ]
