# Generated by Django 4.1.7 on 2023-04-26 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0001_initial'),
        ('posts', '0004_task_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to='experts.experts'),
        ),
    ]
