# Generated by Django 4.1.7 on 2023-03-03 13:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('picture1', models.ImageField(blank=True, default='default.png', null=True, upload_to='blogs/')),
                ('picture2', models.ImageField(blank=True, default='default.png', null=True, upload_to='blogs/')),
                ('picture3', models.ImageField(blank=True, default='default.png', null=True, upload_to='blogs/')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
