# Generated by Django 4.1.7 on 2023-03-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_rename_picture1_blogs_picture_remove_blogs_picture2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/blogs/'),
        ),
    ]
