# Generated by Django 4.1.7 on 2023-04-16 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('categories_image', models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='images/categories')),
            ],
        ),
        migrations.CreateModel(
            name='Experts',
            fields=[
                ('full_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('profile_photo', models.ImageField(blank=True, default='images/experts/profile_photo/user-default.png', null=True, upload_to='images/experts/profile_photo')),
                ('short_intro', models.TextField(blank=True, null=True)),
                ('position', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('github_link', models.URLField(blank=True, max_length=1000, null=True)),
                ('linkedin_link', models.URLField(blank=True, max_length=1000, null=True)),
                ('website_link', models.URLField(blank=True, max_length=1000, null=True)),
                ('twitter_link', models.URLField(blank=True, max_length=1000, null=True)),
                ('youtube_link', models.URLField(blank=True, max_length=1000, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('categories', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='experts.categories')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('experts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='experts.experts')),
            ],
        ),
        migrations.CreateModel(
            name='Experiences',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=100)),
                ('position', models.CharField(blank=True, choices=[('Senior', 'Sr.'), ('Mid Level', 'Mid.'), ('Junior', 'Jr.'), ('Intern', 'Intern')], default='Trainee', max_length=100, null=True)),
                ('duration', models.PositiveSmallIntegerField(default='1')),
                ('is_working', models.BooleanField(default=False)),
                ('experts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='experts.experts')),
            ],
        ),
        migrations.CreateModel(
            name='Educations',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('degree', models.CharField(blank=True, choices=[('Doctorate', 'Doctorate'), ('Master', 'Master'), ('Bachelor', 'Bachelor'), ('Intermediate', 'Intermediate')], default='None', max_length=100, null=True)),
                ('title', models.CharField(max_length=100)),
                ('university_name', models.CharField(blank=True, max_length=100, null=True)),
                ('institute_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('experts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='experts.experts')),
            ],
        ),
    ]
